In [1]:
#funciones trigonometricas 

import numpy as np

# calcuar el seno() pi/2
# sin()

x = np.sin(np.pi/2)
print(x)

a = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
x = np.sin(a)
print(x)

a = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
x = np.cos(a)
print(x)

a = np.array([90,180,270,360])
x = np.deg2rad(a)
print(x)




1.0
[1.         0.8660254  0.70710678 0.58778525]
[6.12323400e-17 5.00000000e-01 7.07106781e-01 8.09016994e-01]
[1.57079633 3.14159265 4.71238898 6.28318531]
