In [1]:
#corte con numpy

import numpy as np
x= np. array([1,2,3,4,5,6,7])
print(x[1:5])
x1= np. array([1,2,3,4,5,6,7])
print(x1[4:])
x2= np. array([0,1,2,3,4,5,6,7])
print(x2[:4])
x3= np. array([1,2,3,4,5,6,7])
print(x3[-3:-1])
x4= np. array([0,1,2,3,4,5,6,7])
print(x4[1:5:2])

[2 3 4 5]
[5 6 7]
[0 1 2 3]
[5 6]
[1 3]
