In [1]:
#Copiar arreglo y vistas de arreglos
import numpy as np
x_original= np.array([1,2,3,4,5])
x_copia= x_original.copy()

x_original[0]=100
x_original[3]=105
print(x_original)
print(x_copia)

[100   2   3 105   5]
[1 2 3 4 5]


In [2]:
import numpy as np
x_original= np.array([1,2,3,4,5,45,63])
vista= x_original. view()
vista[0] =50
print(x_original)
print(vista)


[50  2  3  4  5 45 63]
[50  2  3  4  5 45 63]
