In [1]:
#reformacion de matrices numpy
import numpy as np 

x= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
x= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
reformar= x.reshape(2,6)
print(reformar)
x= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
reformar= x.reshape(2,3,2)
print(reformar)
x= np.array([1,2,3,4,5,6,7,8])
print(x)
reformar= x.reshape(2,2,2)
print(reformar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
