In [1]:
"""ALEJANDRO TRUJANO CHAVEZ"""

import numpy as np
print(np.__version__) #version de numpy

x= np.array([1,2,3,4,5,6,7])
print(x)

x= np.array([1,2,3,4,5,6,7])
print(type(x))

y= np.array((1,2,3,4))
print(type(y))

1.26.1
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Visualizar vectores con numpy

In [2]:
import numpy as np
x= np.array([1,2,3,4,5,6,7])
print(x)

#arreglo de dos dimenciones
x2= np.array([[1,2,3],[4,5,6]])
print(x2)

#acceder elementos de un matriz
x= np.array([1,2,3,4,5,6,7])
print(x[6]) #especificar el nombre del arreglo
#posicion del indice

#operaciones con arreglos
x= np.array([1,2,3,4,])
print(x)
print(x[2] + x[3])

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]]
7
[1 2 3 4]
7
